# Basic configuration for a Quarto website
# --> Render any Quarto markdown files
# --> Do not render any markdown
# files that are in the repository
# as a configuration file for an agent
# (e.g., the GEMINI.md file or the
# AGENTS.md file or the files used for
# tracking tasks like PLAN.md or COMPLETED.md)
project:
  type: website
  preview:
    port: 5556
    browser: false
    watch-inputs: true
    navigate: false
  render:
    - "*.qmd"
    - "!scripts"
    - "!AGENTS.qmd"
    - "!COMPLETED.qmd"
    - "!GEMINI.qmd"
    - "!PLAN.qmd"

# Define all parameters for the website
website:
  title: ""
  search:
    location: navbar
  reader-mode: false
  back-to-top-navigation: true
  page-navigation: true
  favicon: "icons/prosegrammers.png"
  open-graph: true
  site-url: https://www.prosegrammers.com/
  repo-url: https://github.com/prosegrammers/prosegrammers
  navbar:
    left:
      - href: index.qmd
        text: Home
      - syllabus/index.qmd
      - schedule/index.qmd
      - slides/index.qmd

  page-footer:
    left: '<a href="https://github.com/prosegrammers/www.prosegrammers.com/graphs/contributors" aria-label="Prosegrammers Maintainers">{{< iconify fa copyright >}} Prosegrammers</a>'
    right:
      - text: "{{< iconify fa github size=18px >}}"
        href: https://github.com/prosegrammers/
      - text: "{{< iconify fa github-square size=18px >}}"
        href: https://github.com/prosegrammers/www.prosegrammers.com/
      - text: "{{< iconify bi discord size=19px >}}"
        href: https://discord.gg/5HdxuqjUvK

format:
  html:
    # Note that the fonts must also be loaded inside of the
    # css/styles.css file and then declared correctly, at
    # least for the monospace font to work on all platforms
    mainfont: Inter
    monofont: Ubuntu Mono
    fontsize: 1.25em
    theme: zephyr
    highlight-style: github
    css: css/styles.css
    include-in-header:
      # include in the header preconnect and theme-color
      - file: _include/html/header-include.html

execute:
  freeze: auto
